obj-$(CONFIG_MACH_HAS_NEWLIB) += exit.o stdio.o getpid.o kill.o
obj-$(CONFIG_NEWLIB_MALLOC_THREAD_SAFE) += malloc.o
obj-$(CONFIG_MALLOC_1) += malloc_1.o
obj-$(CONFIG_MALLOC_2) += malloc_2.o
obj-$(CONFIG_MALLOC_3) += malloc_3.o
