obj-$(CONFIG_MPU9250) += mpu9250.o mpu9250_accel.o mpu9250_gyro.o
obj-$(CONFIG_ICM20948) += icm20948.o mpu9250_accel.o mpu9250_gyro.o
obj-$(CONFIG_ACCEL) += accel.o
obj-$(CONFIG_GYRO) += gyro.o
obj-$(CONFIG_TEMP) += temp.o
obj-$(CONFIG_TEMP_NTC) += temp_ntc.o
