#ifndef LWIPOPTS_H_
#define LWIPOPTS_H_
#ifdef CONFIG_MACH_NET_DEFAULT_ALGIN
# define MEM_ALIGNMENT CONFIG_MACH_NET_DEFAULT_ALGIN
#else
# define MEM_ALIGNMENT CONFIG_MEM_ALIGNMENT
#endif

#define BYTE_ORDER LITTLE_ENDIAN
#include <inttypes.h>
#define U8_F PRIu8
#define S8_F PRId8
#define X8_F PRIx8
#define U16_F PRIu16
#define S16_F PRId16
#define X16_F PRIx16
#define U32_F PRIu32
#define S32_F PRId32
#define X32_F PRIx32
#define LWIP_PLATFORM_DIAG(opt) do {printf opt;} while (0)

#include <stdlib.h>
#define LWIP_RAND() rand()
#include <stdint.h>
#define INT_MAX INT32_MAX
#define LWIP_PROVIDE_ERRNO 1
/*#define PBUF_POOL_BUFSIZE 2048*/

//%s/CONFIG_\([A-Za-z0-9_]*\)=y/#ifdef CONFIG_\1\r/* define  */\1 1\r#else\r# define \1 0\r#endif/
//%s/#\n//
//%s/# \([A-Za-z0-9\- ]*\)/\/* \1 *\/
/* LWIP Options */

/* Debugging */
#ifdef CONFIG_LWIP_STATS
# define LWIP_STATS 1
#else
# define LWIP_STATS 0
#endif
#ifdef CONFIG_ETHARP_STATS
# define ETHARP_STATS 1
#else
# define ETHARP_STATS 0
#endif
#ifdef CONFIG_ICMP6_STATS
# define ICMP6_STATS 1
#else
# define ICMP6_STATS 0
#endif
#ifdef CONFIG_ICMP_STATS
# define ICMP_STATS 1
#else
# define ICMP_STATS 0
#endif
#ifdef CONFIG_IGMP_STATS
# define IGMP_STATS 1
#else
# define IGMP_STATS 0
#endif
#ifdef CONFIG_IP6_FRAG_STATS
# define IP6_FRAG_STATS 1
#else
# define IP6_FRAG_STATS 0
#endif
#ifdef CONFIG_IP6_STATS
# define IP6_STATS 1
#else
# define IP6_STATS 0
#endif
#ifdef CONFIG_IP_STATS
# define IP_STATS 1
#else
# define IP_STATS 0
#endif
#ifdef CONFIG_IPFRAG_STATS
# define IPFRAG_STATS 1
#else
# define IPFRAG_STATS 0
#endif
#ifdef CONFIG_LINK_STATS
# define LINK_STATS 1
#else
# define LINK_STATS 0
#endif
#ifdef CONFIG_LWIP_STATS_DISPLAY
# define LWIP_STATS_DISPLAY 1
#else
# define LWIP_STATS_DISPLAY 0
#endif
#ifdef CONFIG_MEM_STATS
# define MEM_STATS 1
#else
# define MEM_STATS 0
#endif
#ifdef CONFIG_MIB2_STATS
# define MIB2_STATS 1
#else
# define MIB2_STATS 0
#endif
#ifdef CONFIG_MLD6_STATS
# define MLD6_STATS 1
#else
# define MLD6_STATS 0
#endif
#ifdef CONFIG_ND6_STATS
# define ND6_STATS 1
#else
# define ND6_STATS 0
#endif
#ifdef CONFIG_SYS_STATS
# define SYS_STATS 1
#else
# define SYS_STATS 0
#endif
#ifdef CONFIG_TCP_STATS
# define TCP_STATS 1
#else
# define TCP_STATS 0
#endif
#ifdef CONFIG_UDP_STATS
# define UDP_STATS 1
#else
# define UDP_STATS 0
#endif

/* Debugging */

/* TODO */
#ifdef CONFIG_LWIP_PERF
# define LWIP_PERF 1
#else
# define LWIP_PERF 0
#endif

/* Infrastructure */

/* Timers */
#ifdef CONFIG_LWIP_TIMERS
# define LWIP_TIMERS 1
#else
# define LWIP_TIMERS 0
#endif
#ifdef CONFIG_LWIP_TIMERS_CUSTOM
# define LWIP_TIMERS_CUSTOM 1
#else
# define LWIP_TIMERS_CUSTOM 0
#endif

/* Core locking and MPU */
#ifdef CONFIG_LWIP_MPU_COMPATIBLE
# define LWIP_MPU_COMPATIBLE 1
#else
# define LWIP_MPU_COMPATIBLE 0
#endif
#ifdef CONFIG_LWIP_TCPIP_CORE_LOCKING
# define LWIP_TCPIP_CORE_LOCKING 1
#else
# define LWIP_TCPIP_CORE_LOCKING 0
#endif
#ifdef CONFIG_LWIP_TCPIP_CORE_LOCKING_INPUT
# define LWIP_TCPIP_CORE_LOCKING_INPUT 1
#else
# define LWIP_TCPIP_CORE_LOCKING_INPUT 0
#endif
#ifdef CONFIG_SYS_LIGHTWEIGHT_PROT
# define SYS_LIGHTWEIGHT_PROT 1
#else
# define SYS_LIGHTWEIGHT_PROT 0
#endif

/* Heap and memory pools */
#ifdef CONFIG_LWIP_ALLOW_MEM_FREE_FROM_OTHER_CONTEXT
# define LWIP_ALLOW_MEM_FREE_FROM_OTHER_CONTEXT 1
#else
# define LWIP_ALLOW_MEM_FREE_FROM_OTHER_CONTEXT 0
#endif
#ifdef CONFIG_MEM_LIBC_MALLOC
# define MEM_LIBC_MALLOC 1
#else
# define MEM_LIBC_MALLOC 0
#endif
#ifdef CONFIG_MEM_USE_POOLS
# define MEM_USE_POOLS 1
#else
# define MEM_USE_POOLS 0
#endif
#ifdef CONFIG_MEM_SIZE
# define MEM_SIZE CONFIG_MEM_SIZE
#endif
#ifdef CONFIG_MEMP_MEM_MALLOC
# define MEMP_MEM_MALLOC 1
#else
# define MEMP_MEM_MALLOC 0
#endif
#ifdef CONFIG_MEMP_OVERFLOW_CHECK
# define MEMP_OVERFLOW_CHECK 1
#else
# define MEMP_OVERFLOW_CHECK 0
#endif
#ifdef CONFIG_MEMP_SANITY_CHECK
# define MEMP_SANITY_CHECK 1
#else
# define MEMP_SANITY_CHECK 0
#endif
#ifdef CONFIG_MEMP_USE_CUSTOM_POOLS
# define MEMP_USE_CUSTOM_POOLS 1
#else
# define MEMP_USE_CUSTOM_POOLS 0
#endif

/* Internal memory pools */
#define MEMP_NUM_ARP_QUEUE CONFIG_MEMP_NUM_ARP_QUEUE
#define MEMP_NUM_FRAG_PBUF CONFIG_MEMP_NUM_FRAG_PBUF
#define MEMP_NUM_IGMP_GROUP CONFIG_MEMP_NUM_IGMP_GROUP
#define MEMP_NUM_LOCALHOSTLIST CONFIG_MEMP_NUM_LOCALHOSTLIST
#define MEMP_NUM_NETBUF CONFIG_MEMP_NUM_NETBUF
#define MEMP_NUM_NETCONN CONFIG_MEMP_NUM_NETCONN
#define MEMP_NUM_NETDB CONFIG_MEMP_NUM_NETDB
#define MEMP_NUM_PBUF CONFIG_MEMP_NUM_PBUF
#define MEMP_NUM_RAW_PCB CONFIG_MEMP_NUM_RAW_PCB
#define MEMP_NUM_REASSDATA CONFIG_MEMP_NUM_REASSDATA
#define MEMP_NUM_TCP_PCB CONFIG_MEMP_NUM_TCP_PCB
#define MEMP_NUM_TCP_PCB_LISTEN CONFIG_MEMP_NUM_TCP_PCB_LISTEN
#define MEMP_NUM_TCP_SEG CONFIG_MEMP_NUM_TCP_SEG
#define MEMP_NUM_TCPIP_MSG_API CONFIG_MEMP_NUM_TCPIP_MSG_API
#define MEMP_NUM_TCPIP_MSG_INPKT CONFIG_MEMP_NUM_TCPIP_MSG_INPKT
#define MEMP_NUM_UDP_PCB CONFIG_MEMP_NUM_UDP_PCB
#define PBUF_POOL_SIZE CONFIG_PBUF_POOL_SIZE

/* SNMP MIB2 callbacks */
#ifdef CONFIG_LWIP_MIB2_CALLBACKS
# define LWIP_MIB2_CALLBACKS 1
#else
# define LWIP_MIB2_CALLBACKS 0
#endif

/* Threading */
#define DEFAULT_ACCEPTMBOX_SIZE CONFIG_DEFAULT_ACCEPTMBOX_SIZE
#define DEFAULT_RAW_RECVMBOX_SIZE CONFIG_DEFAULT_RAW_RECVMBOX_SIZE
#define DEFAULT_TCP_RECVMBOX_SIZE CONFIG_DEFAULT_TCP_RECVMBOX_SIZE
#define DEFAULT_THREAD_NAME CONFIG_DEFAULT_THREAD_NAME"LwIP"
#define DEFAULT_THREAD_PRIO CONFIG_DEFAULT_THREAD_PRIO
#define DEFAULT_THREAD_STACKSIZE CONFIG_DEFAULT_THREAD_STACKSIZE
#define DEFAULT_UDP_RECVMBOX_SIZE CONFIG_DEFAULT_UDP_RECVMBOX_SIZE
#define SLIPIF_THREAD_NAME CONFIG_SLIPIF_THREAD_NAME"slipif_loop"
#define SLIPIF_THREAD_PRIO CONFIG_SLIPIF_THREAD_PRIO
#define SLIPIF_THREAD_STACKSIZE CONFIG_SLIPIF_THREAD_STACKSIZE
#define TCPIP_MBOX_SIZE CONFIG_TCPIP_MBOX_SIZE
#define TCPIP_THREAD_NAME CONFIG_TCPIP_THREAD_NAME"tcpip_thread"
#define TCPIP_THREAD_PRIO CONFIG_TCPIP_THREAD_PRIO
#define TCPIP_THREAD_STACKSIZE CONFIG_TCPIP_THREAD_STACKSIZE

/* Checksum */
#ifdef CONFIG_CHECKSUM_CHECK_ICMP
# define CHECKSUM_CHECK_ICMP 1
#else
# define CHECKSUM_CHECK_ICMP 0
#endif
#ifdef CONFIG_CHECKSUM_CHECK_ICMP6
# define CHECKSUM_CHECK_ICMP6 1
#else
# define CHECKSUM_CHECK_ICMP6 0
#endif
#ifdef CONFIG_CHECKSUM_CHECK_IP
# define CHECKSUM_CHECK_IP 1
#else
# define CHECKSUM_CHECK_IP 0
#endif
#ifdef CONFIG_CHECKSUM_CHECK_TCP
# define CHECKSUM_CHECK_TCP 1
#else
# define CHECKSUM_CHECK_TCP 0
#endif
#ifdef CONFIG_CHECKSUM_CHECK_UDP
# define CHECKSUM_CHECK_UDP 1
#else
# define CHECKSUM_CHECK_UDP 0
#endif
#ifdef CONFIG_CHECKSUM_GEN_ICMP
# define CHECKSUM_GEN_ICMP 1
#else
# define CHECKSUM_GEN_ICMP 0
#endif
#ifdef CONFIG_CHECKSUM_GEN_ICMP6
# define CHECKSUM_GEN_ICMP6 1
#else
# define CHECKSUM_GEN_ICMP6 0
#endif
#ifdef CONFIG_CHECKSUM_GEN_IP
# define CHECKSUM_GEN_IP 1
#else
# define CHECKSUM_GEN_IP 0
#endif
#ifdef CONFIG_CHECKSUM_GEN_TCP
# define CHECKSUM_GEN_TCP 1
#else
# define CHECKSUM_GEN_TCP 0
#endif
#ifdef CONFIG_CHECKSUM_GEN_UDP
# define CHECKSUM_GEN_UDP 1
#else
# define CHECKSUM_GEN_UDP 0
#endif
#ifdef CONFIG_LWIP_CHECKSUM_CTRL_PER_NETIF
# define LWIP_CHECKSUM_CTRL_PER_NETIF 1
#else
# define LWIP_CHECKSUM_CTRL_PER_NETIF 0
#endif
#ifdef CONFIG_LWIP_CHECKSUM_ON_COPY
# define LWIP_CHECKSUM_ON_COPY 1
#else
# define LWIP_CHECKSUM_ON_COPY 0
#endif

/* Callback -style APIs */
#ifdef CONFIG_LWIP_RAW
# define LWIP_RAW 1
#else
# define LWIP_RAW 0
#endif
#ifdef CONFIG_LWIP_DNS
# define LWIP_DNS 1
#else
# define LWIP_DNS 0
#endif
#ifdef CONFIG_DNS_DOES_NAME_CHECK
# define DNS_DOES_NAME_CHECK 1
#else
# define DNS_DOES_NAME_CHECK 0
#endif
#ifdef CONFIG_DNS_LOCAL_HOSTLIST
# define DNS_LOCAL_HOSTLIST 1
#else
# define DNS_LOCAL_HOSTLIST 0
#endif
#ifdef CONFIG_DNS_LOCAL_HOSTLIST_IS_DYNAMIC
# define DNS_LOCAL_HOSTLIST_IS_DYNAMIC 1
#else
# define DNS_LOCAL_HOSTLIST_IS_DYNAMIC 0
#endif
#define DNS_MAX_NAME_LENGTH CONFIG_DNS_MAX_NAME_LENGTH
#define DNS_MAX_SERVERS CONFIG_DNS_MAX_SERVERS
#define DNS_TABLE_SIZE CONFIG_DNS_TABLE_SIZE
#ifdef CONFIG_LWIP_UDP
# define LWIP_UDP 1
#else
# define LWIP_UDP 0
#endif
#ifdef CONFIG_LWIP_NETBUF_RECVINFO
# define LWIP_NETBUF_RECVINFO 1
#else
# define LWIP_NETBUF_RECVINFO 0
#endif
#ifdef CONFIG_LWIP_UDPLITE
# define LWIP_UDPLITE 1
#else
# define LWIP_UDPLITE 0
#endif
#ifdef CONFIG_LWIP_TCP
# define LWIP_TCP 1
#else
# define LWIP_TCP 0
#endif
#ifdef CONFIG_LWIP_EVENT_API
# define LWIP_EVENT_API 1
#else
# define LWIP_EVENT_API 0
#endif
#ifdef CONFIG_LWIP_CALLBACK_API
# define LWIP_CALLBACK_API 1
#else
# define LWIP_CALLBACK_API 0
#endif
#ifdef CONFIG_LWIP_TCP_TIMESTAMPS
# define LWIP_TCP_TIMESTAMPS 1
#else
# define LWIP_TCP_TIMESTAMPS 0
#endif
#define LWIP_WND_SCALE CONFIG_LWIP_WND_SCALE
#define TCP_CALCULATE_EFF_SEND_MSS CONFIG_TCP_CALCULATE_EFF_SEND_MSS
#define TCP_DEFAULT_LISTEN_BACKLOGTCP_DEFAULT_LISTEN_BACKLOG CONFIG_TCP_DEFAULT_LISTEN_BACKLOGTCP_DEFAULT_LISTEN_BACKLOGxff
#ifdef CONFIG_TCP_LISTEN_BACKLOG
# define TCP_LISTEN_BACKLOG 1
#else
# define TCP_LISTEN_BACKLOG 0
#endif
#define TCP_MAXRTX CONFIG_TCP_MAXRTX
#define TCP_MSS CONFIG_TCP_MSS
#define TCP_OOSEQ_MAX_BYTES CONFIG_TCP_OOSEQ_MAX_BYTES
#define TCP_OOSEQ_MAX_PBUFS CONFIG_TCP_OOSEQ_MAX_PBUFS
#define TCP_SYNMAXRTX CONFIG_TCP_SYNMAXRTX

/* Thread -safe APIs */
#ifdef CONFIG_LWIP_NETCONN
# define LWIP_NETCONN 1
#else
# define LWIP_NETCONN 0
#endif
#ifdef CONFIG_LWIP_NETCONN_FULLDUPLEX
# define LWIP_NETCONN_FULLDUPLEX 1
#else
# define LWIP_NETCONN_FULLDUPLEX 0
#endif
#ifdef CONFIG_LWIP_NETCONN_SEM_PER_THREAD
# define LWIP_NETCONN_SEM_PER_THREAD 1
#else
# define LWIP_NETCONN_SEM_PER_THREAD 0
#endif
#ifdef CONFIG_LWIP_TCPIP_TIMEOUT
# define LWIP_TCPIP_TIMEOUT 1
#else
# define LWIP_TCPIP_TIMEOUT 0
#endif
#ifdef CONFIG_LWIP_SOCKET
# define LWIP_SOCKET 1
#else
# define LWIP_SOCKET 0
#endif
#ifdef CONFIG_LWIP_COMPAT_SOCKETS
# define LWIP_COMPAT_SOCKETS 1
#else
# define LWIP_COMPAT_SOCKETS 0
#endif
#ifdef CONFIG_LWIP_FIONREAD_LINUXMODE
# define LWIP_FIONREAD_LINUXMODE 1
#else
# define LWIP_FIONREAD_LINUXMODE 0
#endif
#ifdef CONFIG_LWIP_POSIX_SOCKETS_IO_NAMES
# define LWIP_POSIX_SOCKETS_IO_NAMES 1
#else
# define LWIP_POSIX_SOCKETS_IO_NAMES 0
#endif
#ifdef CONFIG_LWIP_SO_LINGER
# define LWIP_SO_LINGER 1
#else
# define LWIP_SO_LINGER 0
#endif
#ifdef CONFIG_LWIP_SO_RCVBUF
# define LWIP_SO_RCVBUF 1
#else
# define LWIP_SO_RCVBUF 0
#endif
#ifdef CONFIG_LWIP_SO_RCVTIMEO
# define LWIP_SO_RCVTIMEO 1
#else
# define LWIP_SO_RCVTIMEO 0
#endif
#ifdef CONFIG_LWIP_SO_SNDRCVTIMEO_NONSTANDARD
# define LWIP_SO_SNDRCVTIMEO_NONSTANDARD 1
#else
# define LWIP_SO_SNDRCVTIMEO_NONSTANDARD 0
#endif
#ifdef CONFIG_LWIP_SO_SNDTIMEO
# define LWIP_SO_SNDTIMEO 1
#else
# define LWIP_SO_SNDTIMEO 0
#endif
#define LWIP_SOCKET_OFFSET CONFIG_LWIP_SOCKET_OFFSET
#ifdef CONFIG_LWIP_TIMEVAL_PRIVATE
# define LWIP_TIMEVAL_PRIVATE 1
#else
# define LWIP_TIMEVAL_PRIVATE 0
#endif
#define LWIP_TCP_CLOSE_TIMEOUT_MS_DEFAULT CONFIG_LWIP_TCP_CLOSE_TIMEOUT_MS_DEFAULT
#ifdef CONFIG_LWIP_TCP_KEEPALIVE
# define LWIP_TCP_KEEPALIVE 1
#else
# define LWIP_TCP_KEEPALIVE 0
#endif
#ifdef CONFIG_SO_REUSE
# define SO_REUSE 1
#else
# define SO_REUSE 0
#endif
#ifdef CONFIG_SO_REUSE_RXTOALL
# define SO_REUSE_RXTOALL 1
#else
# define SO_REUSE_RXTOALL 0
#endif
#ifdef CONFIG_LWIP_IPV4
# define LWIP_IPV4 1
#else
# define LWIP_IPV4 0
#endif
#define IP_DEFAULT_TTL CONFIG_IP_DEFAULT_TTL
#ifdef CONFIG_IP_FORWARD
# define IP_FORWARD 1
#else
# define IP_FORWARD 0
#endif
#ifdef CONFIG_IP_FORWARD_ALLOW_TX_ON_RX_NETIF
# define IP_FORWARD_ALLOW_TX_ON_RX_NETIF 1
#else
# define IP_FORWARD_ALLOW_TX_ON_RX_NETIF 0
#endif
#ifdef CONFIG_IP_FRAG
# define IP_FRAG 1
#else
# define IP_FRAG 0
#endif
#define IP_FRAG_MAX_MTU CONFIG_IP_FRAG_MAX_MTU
#ifdef CONFIG_IP_FRAG_USES_STATIC_BUF
# define IP_FRAG_USES_STATIC_BUF 1
#else
# define IP_FRAG_USES_STATIC_BUF 0
#endif
#ifdef CONFIG_IP_OPTIONS_ALLOWED
# define IP_OPTIONS_ALLOWED 1
#else
# define IP_OPTIONS_ALLOWED 0
#endif
#define IP_REASS_MAX_PBUFS CONFIG_IP_REASS_MAX_PBUFS
#define IP_REASS_MAXAGE CONFIG_IP_REASS_MAXAGE
#ifdef CONFIG_IP_REASSEMBLY
# define IP_REASSEMBLY 1
#else
# define IP_REASSEMBLY 0
#endif
#ifdef CONFIG_IP_SOF_BROADCAST
# define IP_SOF_BROADCAST 1
#else
# define IP_SOF_BROADCAST 0
#endif
#ifdef CONFIG_IP_SOF_BROADCAST_RECV
# define IP_SOF_BROADCAST_RECV 1
#else
# define IP_SOF_BROADCAST_RECV 0
#endif
#ifdef CONFIG_LWIP_RANDOMIZE_INITIAL_LOCAL_PORTS
# define LWIP_RANDOMIZE_INITIAL_LOCAL_PORTS 1
#else
# define LWIP_RANDOMIZE_INITIAL_LOCAL_PORTS 0
#endif
#ifdef CONFIG_LWIP_ARP
# define LWIP_ARP 1
#else
# define LWIP_ARP 0
#endif
#define ARP_MAXAGE CONFIG_ARP_MAXAGE
#define ARP_QUEUE_LEN CONFIG_ARP_QUEUE_LEN
#ifdef CONFIG_ARP_QUEUEING
# define ARP_QUEUEING 1
#else
# define ARP_QUEUEING 0
#endif
#define ARP_TABLE_SIZE CONFIG_ARP_TABLE_SIZE
#define ETH_PAD_SIZE CONFIG_ETH_PAD_SIZE
#ifdef CONFIG_ETHARP_SUPPORT_STATIC_ENTRIES
# define ETHARP_SUPPORT_STATIC_ENTRIES 1
#else
# define ETHARP_SUPPORT_STATIC_ENTRIES 0
#endif
#ifdef CONFIG_ETHARP_SUPPORT_VLAN
# define ETHARP_SUPPORT_VLAN 1
#else
# define ETHARP_SUPPORT_VLAN 0
#endif
#ifdef CONFIG_ETHARP_TABLE_MATCH_NETIF
# define ETHARP_TABLE_MATCH_NETIF 1
#else
# define ETHARP_TABLE_MATCH_NETIF 0
#endif
#ifdef CONFIG_ETHARP_TRUST_IP_MAC
# define ETHARP_TRUST_IP_MAC 1
#else
# define ETHARP_TRUST_IP_MAC 0
#endif
#ifdef CONFIG_LWIP_ETHERNET
# define LWIP_ETHERNET 1
#else
# define LWIP_ETHERNET 0
#endif
#ifdef CONFIG_LWIP_ICMP
# define LWIP_ICMP 1
#else
# define LWIP_ICMP 0
#endif
#ifdef CONFIG_LWIP_BROADCAST_PING
# define LWIP_BROADCAST_PING 1
#else
# define LWIP_BROADCAST_PING 0
#endif
#ifdef CONFIG_LWIP_MULTICAST_PING
# define LWIP_MULTICAST_PING 1
#else
# define LWIP_MULTICAST_PING 0
#endif
#ifdef CONFIG_LWIP_DHCP
# define LWIP_DHCP 1
#else
# define LWIP_DHCP 0
#endif
#ifdef CONFIG_LWIP_DHCP_BOOTP_FILE
# define LWIP_DHCP_BOOTP_FILE 1
#else
# define LWIP_DHCP_BOOTP_FILE 0
#endif
#ifdef CONFIG_LWIP_DHCP_GET_NTP_SRV
# define LWIP_DHCP_GET_NTP_SRV 1
#else
# define LWIP_DHCP_GET_NTP_SRV 0
#endif
#ifdef CONFIG_LWIP_DHCP_MAX_NTP_SERVERS
# define LWIP_DHCP_MAX_NTP_SERVERS 1
#else
# define LWIP_DHCP_MAX_NTP_SERVERS 0
#endif
#ifdef CONFIG_LWIP_AUTOIP
# define LWIP_AUTOIP 1
#else
# define LWIP_AUTOIP 0
#endif
#ifdef CONFIG_LWIP_DHCP_AUTOIP_COOP
# define LWIP_DHCP_AUTOIP_COOP 1
#else
# define LWIP_DHCP_AUTOIP_COOP 0
#endif
#define LWIP_DHCP_AUTOIP_COOP_TRIES CONFIG_LWIP_DHCP_AUTOIP_COOP_TRIES
#ifdef CONFIG_LWIP_IGMP
# define LWIP_IGMP 1
#else
# define LWIP_IGMP 0
#endif
#ifdef CONFIG_LWIP_MULTICAST_TX_OPTIONS
# define LWIP_MULTICAST_TX_OPTIONS 1
#else
# define LWIP_MULTICAST_TX_OPTIONS 0
#endif

/* PBUF */
#define PBUF_LINK_ENCAPSULATION_HLEN CONFIG_PBUF_LINK_ENCAPSULATION_HLEN
#ifdef CONFIG_LWIP_NETIF_API
# define LWIP_NETIF_API 1
#else
# define LWIP_NETIF_API 0
#endif
#ifdef CONFIG_LWIP_NETIF_HOSTNAME
# define LWIP_NETIF_HOSTNAME 1
#else
# define LWIP_NETIF_HOSTNAME 0
#endif
#ifdef CONFIG_LWIP_NETIF_HWADDRHINT
# define LWIP_NETIF_HWADDRHINT 1
#else
# define LWIP_NETIF_HWADDRHINT 0
#endif
#ifdef CONFIG_LWIP_NETIF_LINK_CALLBACK
# define LWIP_NETIF_LINK_CALLBACK 1
#else
# define LWIP_NETIF_LINK_CALLBACK 0
#endif
#ifdef CONFIG_LWIP_NETIF_REMOVE_CALLBACK
# define LWIP_NETIF_REMOVE_CALLBACK 1
#else
# define LWIP_NETIF_REMOVE_CALLBACK 0
#endif
#ifdef CONFIG_LWIP_NETIF_STATUS_CALLBACK
# define LWIP_NETIF_STATUS_CALLBACK 1
#else
# define LWIP_NETIF_STATUS_CALLBACK 0
#endif
#ifdef CONFIG_LWIP_NETIF_TX_SINGLE_PBUF
# define LWIP_NETIF_TX_SINGLE_PBUF 1
#else
# define LWIP_NETIF_TX_SINGLE_PBUF 0
#endif
#ifdef CONFIG_LWIP_IPV6
# define LWIP_IPV6 1
#else
# define LWIP_IPV6 0
#endif
#ifdef CONFIG_LWIP_IPV6_AUTOCONFIG
# define LWIP_IPV6_AUTOCONFIG 1
#else
# define LWIP_IPV6_AUTOCONFIG 0
#endif
#ifdef CONFIG_LWIP_IPV6_DUP_DETECT_ATTEMPTS
# define LWIP_IPV6_DUP_DETECT_ATTEMPTS 1
#else
# define LWIP_IPV6_DUP_DETECT_ATTEMPTS 0
#endif
#ifdef CONFIG_LWIP_IPV6_FORWARD
# define LWIP_IPV6_FORWARD 1
#else
# define LWIP_IPV6_FORWARD 0
#endif
#ifdef CONFIG_LWIP_IPV6_FRAG
# define LWIP_IPV6_FRAG 1
#else
# define LWIP_IPV6_FRAG 0
#endif
#define LWIP_IPV6_NUM_ADDRESSES CONFIG_LWIP_IPV6_NUM_ADDRESSES
#ifdef CONFIG_LWIP_IPV6_REASS
# define LWIP_IPV6_REASS 1
#else
# define LWIP_IPV6_REASS 0
#endif
#ifdef CONFIG_LWIP_IPV6_SEND_ROUTER_SOLICIT
# define LWIP_IPV6_SEND_ROUTER_SOLICIT 1
#else
# define LWIP_IPV6_SEND_ROUTER_SOLICIT 0
#endif
#ifdef CONFIG_LWIP_ICMP6
# define LWIP_ICMP6 1
#else
# define LWIP_ICMP6 0
#endif
#define LWIP_ICMP6_DATASIZE CONFIG_LWIP_ICMP6_DATASIZE
#define LWIP_ICMP6_HL CONFIG_LWIP_ICMP6_HL
#ifdef CONFIG_LWIP_IPV6_MLD
# define LWIP_IPV6_MLD 1
#else
# define LWIP_IPV6_MLD 0
#endif
#define MEMP_NUM_MLD6_GROUP CONFIG_MEMP_NUM_MLD6_GROUP
#ifdef CONFIG_LWIP_ND6_QUEUEING
# define LWIP_ND6_QUEUEING 1
#else
# define LWIP_ND6_QUEUEING 0
#endif
#define LWIP_ND6_ALLOW_RA_UPDATES CONFIG_LWIP_ND6_ALLOW_RA_UPDATES
#define LWIP_ND6_MAX_ANYCAST_DELAY_TIME CONFIG_LWIP_ND6_MAX_ANYCAST_DELAY_TIME
#define LWIP_ND6_MAX_MULTICAST_SOLICIT CONFIG_LWIP_ND6_MAX_MULTICAST_SOLICIT
#define LWIP_ND6_MAX_NEIGHBOR_ADVERTISEMENT CONFIG_LWIP_ND6_MAX_NEIGHBOR_ADVERTISEMENT
#define LWIP_ND6_MAX_UNICAST_SOLICIT CONFIG_LWIP_ND6_MAX_UNICAST_SOLICIT
#define LWIP_ND6_NUM_DESTINATIONS CONFIG_LWIP_ND6_NUM_DESTINATIONS
#define LWIP_ND6_NUM_NEIGHBORS CONFIG_LWIP_ND6_NUM_NEIGHBORS
#define LWIP_ND6_NUM_PREFIXES CONFIG_LWIP_ND6_NUM_PREFIXES
#define LWIP_ND6_NUM_ROUTERS CONFIG_LWIP_ND6_NUM_ROUTERS
#define LWIP_ND6_REACHABLE_TIME CONFIG_LWIP_ND6_REACHABLE_TIME
#define LWIP_ND6_RETRANS_TIMER CONFIG_LWIP_ND6_RETRANS_TIMER
#define LWIP_ND6_TCP_REACHABILITY_HINTS CONFIG_LWIP_ND6_TCP_REACHABILITY_HINTS
#define MEMP_NUM_ND6_QUEUE CONFIG_MEMP_NUM_ND6_QUEUE
#ifdef CONFIG_LWIP_PPP
# define LWIP_PPP 1
#else
# define LWIP_PPP 0
#endif
#ifdef CONFIG_LWIP_HTTP
# define LWIP_HTTP 1
#else
# define LWIP_HTTP 0
#endif
#ifdef CONFIG_LWIP_IPERF
# define LWIP_IPERF 1
#else
# define LWIP_IPERF 0
#endif
#ifdef CONFIG_LWIP_SNTP
# define LWIP_SNTP 1
#else
# define LWIP_SNTP 0
#endif
#ifdef CONFIG_LWIP_NETBIOS
# define LWIP_NETBIOS 1
#else
# define LWIP_NETBIOS 0
#endif

#endif
