obj-$(CONFIG_NET) += net.o
obj-$(CONFIG_NET_DUMMY) += net_dummy.o
obj-$(CONFIG_NET_VLAN) += vlan.o
obj-$(CONFIG_MAC) += mac.o
obj-$(CONFIG_PHYLIB) += phy/
obj-$(CONFIG_LWIP) += lwip/
obj-$(CONFIG_NET_PTP) += ptpd.o
